// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDagrVg0y4Kdv9KXzR09R2kUhrzTRXDDqI',
    appId: '1:423364430204:web:b46f7ac93980e01b05bcf9',
    messagingSenderId: '423364430204',
    projectId: 'signbridge-8d0d3',
    authDomain: 'signbridge-8d0d3.firebaseapp.com',
    storageBucket: 'signbridge-8d0d3.firebasestorage.app',
    measurementId: 'G-WVNHL28JKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHhepiyCdwWecFRhabQ7eU7NaRaTT7ds0',
    appId: '1:423364430204:android:3671de20de3da87705bcf9',
    messagingSenderId: '423364430204',
    projectId: 'signbridge-8d0d3',
    storageBucket: 'signbridge-8d0d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbvN3H8kp7QfYAYUz4ZS7PCMAXLlk7N0I',
    appId: '1:423364430204:ios:3af1dc47f0a0f16a05bcf9',
    messagingSenderId: '423364430204',
    projectId: 'signbridge-8d0d3',
    storageBucket: 'signbridge-8d0d3.firebasestorage.app',
    iosBundleId: 'com.example.signbridgeUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbvN3H8kp7QfYAYUz4ZS7PCMAXLlk7N0I',
    appId: '1:423364430204:ios:3af1dc47f0a0f16a05bcf9',
    messagingSenderId: '423364430204',
    projectId: 'signbridge-8d0d3',
    storageBucket: 'signbridge-8d0d3.firebasestorage.app',
    iosBundleId: 'com.example.signbridgeUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDagrVg0y4Kdv9KXzR09R2kUhrzTRXDDqI',
    appId: '1:423364430204:web:c2b3fb565a6f006e05bcf9',
    messagingSenderId: '423364430204',
    projectId: 'signbridge-8d0d3',
    authDomain: 'signbridge-8d0d3.firebaseapp.com',
    storageBucket: 'signbridge-8d0d3.firebasestorage.app',
    measurementId: 'G-N9026DGTFL',
  );
}
